# Generated by Django 5.2.8 on 2025-11-19 07:35

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('site_ifo', models.JSONField(blank=True, default=dict)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.FloatField()),
                ('height', models.FloatField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('tank_info', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='flowboard.site')),
            ],
        ),
        migrations.CreateModel(
            name='Sensor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('sensor_type', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sensor_info', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_sensors', to='flowboard.site')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_sensors', to='flowboard.tank')),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('flow_rate', models.FloatField()),
                ('pump_state', models.BooleanField(default=False)),
                ('pump_power_state', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('pump_log', models.JSONField(blank=True, default=dict)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_pumps', to='flowboard.site')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_tank', to='flowboard.tank')),
            ],
        ),
    ]
