# Generated by Django 5.2.8 on 2025-11-11 13:36

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('site_code', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('access_level', models.CharField(blank=True, max_length=50)),
                ('organization', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('equipment_id', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('total_height_mm', models.PositiveIntegerField(help_text='Total tank height in mm (provided by user)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tanks', to='flowboard.site')),
            ],
            options={
                'unique_together': {('site', 'equipment_id')},
            },
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pump_id', models.CharField(blank=True, max_length=200)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pumps', to='flowboard.site')),
                ('tank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pumps', to='flowboard.tank')),
            ],
            options={
                'unique_together': {('site', 'pump_id')},
            },
        ),
        migrations.AddField(
            model_name='site',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sites', to='flowboard.user'),
        ),
        migrations.CreateModel(
            name='UserDevice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('device_id', models.CharField(max_length=200, unique=True)),
                ('device_type', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devices', to='flowboard.site')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='devices', to='flowboard.user')),
            ],
        ),
        migrations.CreateModel(
            name='PumpRunEvent',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('start_time', models.DateTimeField()),
                ('stop_time', models.DateTimeField(blank=True, null=True)),
                ('duration_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='run_events', to='flowboard.pump')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_run_events', to='flowboard.site')),
            ],
            options={
                'indexes': [models.Index(fields=['pump', 'start_time'], name='flowboard_p_pump_id_d53b91_idx')],
            },
        ),
        migrations.CreateModel(
            name='TankMeasurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('distance_mm', models.IntegerField(blank=True, null=True)),
                ('tank_level_mm', models.IntegerField(blank=True, null=True)),
                ('tank_level_percent', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('pump_status_snapshot', models.JSONField(blank=True, help_text='{"pump_1":"ON","pump_2":"OFF"}', null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_measurements', to='flowboard.site')),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='flowboard.tank')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tank_measurements', to='flowboard.userdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'timestamp'], name='flowboard_t_site_id_8c4a44_idx'), models.Index(fields=['tank', 'timestamp'], name='flowboard_t_tank_id_32cbbf_idx'), models.Index(fields=['device', 'timestamp'], name='flowboard_t_device__d6671b_idx')],
                'unique_together': {('tank', 'timestamp')},
            },
        ),
        migrations.CreateModel(
            name='SensorLog',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('payload', models.JSONField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('site', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='flowboard.site')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='logs', to='flowboard.userdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['site', 'timestamp'], name='flowboard_s_site_id_cf0854_idx'), models.Index(fields=['device', 'timestamp'], name='flowboard_s_device__cd360d_idx')],
            },
        ),
        migrations.CreateModel(
            name='PumpMeasurement',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('timestamp', models.DateTimeField()),
                ('status', models.CharField(choices=[('ON', 'ON'), ('OFF', 'OFF')], max_length=5)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='measurements', to='flowboard.pump')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_measurements', to='flowboard.site')),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pump_measurements', to='flowboard.userdevice')),
            ],
            options={
                'indexes': [models.Index(fields=['pump', 'timestamp'], name='flowboard_p_pump_id_72ca10_idx'), models.Index(fields=['site', 'timestamp'], name='flowboard_p_site_id_f13b86_idx')],
                'unique_together': {('pump', 'timestamp')},
            },
        ),
    ]
