# Generated by Django 5.2.8 on 2025-11-19 09:39

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowboard', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pump',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='pump_log',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='pump_power_state',
        ),
        migrations.RemoveField(
            model_name='pump',
            name='pump_state',
        ),
        migrations.RemoveField(
            model_name='tank',
            name='tank_info',
        ),
        migrations.AlterField(
            model_name='sensor',
            name='sensor_type',
            field=models.CharField(blank=True, default='ultrasonic', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='pumpReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('flow_rate_lpm', models.FloatField()),
                ('pump_on', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('pump', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pump_readings', to='flowboard.pump')),
            ],
        ),
        migrations.CreateModel(
            name='TankReading',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('water_level_cm', models.FloatField()),
                ('water_level_perc', models.FloatField()),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tank_readings', to='flowboard.tank')),
            ],
        ),
    ]
