# Generated by Django 5.2.8 on 2025-11-11 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowboard', '0002_sensore_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpmeasurement',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='pumprunevent',
            name='start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
