# Generated by Django 5.2.8 on 2025-11-19 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowboard', '0003_alter_pump_id_alter_pumpreading_id_alter_sensor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pumpreading',
            name='flow_rate_lpm',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
    ]
