# Generated by Django 5.2.8 on 2025-11-20 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flowboard', '0004_alter_pumpreading_flow_rate_lpm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tankreading',
            name='water_level_cm',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='tankreading',
            name='water_level_perc',
            field=models.CharField(blank=True, default='0', max_length=20, null=True),
        ),
    ]
